/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ui;

import javax.swing.BoxLayout;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author USER
 */
public class MessageBox extends javax.swing.JPanel {

    /**
     * Creates new form MessageBox
     */
    public MessageBox(String sender, String recipient, String message, String username) {
        initComponents();
        
        init();
        
        
        labelMessage.setText(message);
        labelSender.setText(sender + " > " + recipient + " :");
    }

    private void init()
    {
        panelMessageBox.setBorder(new EmptyBorder(0,0,0,0));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSender = new javax.swing.JLabel();
        panelMessageBox = new javax.swing.JPanel();
        labelMessage = new javax.swing.JLabel();

        setOpaque(false);

        labelSender.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        labelSender.setForeground(new java.awt.Color(153, 153, 153));
        labelSender.setText("jLabel1");

        panelMessageBox.setBackground(new java.awt.Color(153, 0, 153));
        panelMessageBox.setForeground(new java.awt.Color(153, 0, 153));

        labelMessage.setForeground(new java.awt.Color(255, 255, 255));
        labelMessage.setText("jLabel2");

        javax.swing.GroupLayout panelMessageBoxLayout = new javax.swing.GroupLayout(panelMessageBox);
        panelMessageBox.setLayout(panelMessageBoxLayout);
        panelMessageBoxLayout.setHorizontalGroup(
            panelMessageBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMessageBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMessage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMessageBoxLayout.setVerticalGroup(
            panelMessageBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMessageBoxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelMessage)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSender)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panelMessageBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(labelSender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMessageBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelMessage;
    private javax.swing.JLabel labelSender;
    private javax.swing.JPanel panelMessageBox;
    // End of variables declaration//GEN-END:variables
}
